Unify copyright statement formats and text
oracle/weblogic-monitoring-exporter pull request #133
Opened 2020-12-10 20:45 UTC by ddsharpe

2020-12-11 13:28 UTC, rosemarymarano reviewed
According to http://pdb.us.oracle.com/downloads/legal_notices.html, the copyright statement does not include the word Corporation after Oracle: 
Copyright © [year,] year, Oracle and/or its affiliates.

2020-12-14 15:37 UTC, mriccell requested changes

2020-12-14 15:37 UTC, mriccell commented on samples/configurations/jvm.yml
>  # Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
The license must be https://oss.oracle.com/licenses/upl

2020-12-14 15:37 UTC, mriccell commented on samples/configurations/qualified.yml
>  # Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
https

2020-12-14 15:38 UTC, mriccell commented
Every where you have a Licensing statement the URL must change from http to https

2020-12-14 17:11 UTC, ddsharpe commented on samples/configurations/qualified.yml
>  # Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
done

2020-12-14 17:14 UTC, mriccell approved these changes

2020-12-14 17:19 UTC, rosemarymarano approved these changes
Looks like you got them all.

2020-12-14 18:12 UTC, merged