Update 03-wls-operator.md
oracle/weblogic-monitoring-exporter pull request #154
Opened 2021-06-23 16:03 UTC by Anjali93

2021-06-23 16:49 UTC, ddsharpe requested changes

2021-06-23 16:49 UTC, ddsharpe commented on samples/kubernetes/end2end/docs/03-wls-operator.md
> +for logging into oracle registry use with sso creds use:  docker login container-registry.oracle.com
Each of these lines is executable, and this additional line is not.  This is not the correct location for this comment.

2021-06-23 16:51 UTC, ddsharpe commented
@Anjali93 This commit needs to be signed before it can be accepted.  Please review the document at https://github.com/oracle/weblogic-monitoring-exporter/blob/master/CONTRIBUTING.md

2021-12-16 18:37 UTC, robertpatrick commented
Is this PR still relevant?  If so, please address the change requested.  If not, please close it.  Please note that we will have to close this PR if there continues to be no response.

2021-12-21 21:06 UTC, ddsharpe commented
Closing due to lack of response.  Please reopen or re-file if still desired.

2021-12-21 21:06 UTC, closed without merging